/**
 * profileEmit — structured JSONL emitter for Orca latency profiling.
 *
 * Gated behind ORCA_PROFILE=1 — completely inert in normal runs.
 *
 * Usage:
 *   ORCA_PROFILE=1 node --experimental-strip-types apps/runner/src/tracer.ts "prompt"
 *
 * Output written to: profile-runs/<timestamp>.jsonl
 * Report generated by: scripts/profiling/analyze.ts
 *
 * Instrumented phases (set up by initProfiler):
 *   run:start / run:end          — full pipeline wall-clock boundary
 *   llm_call                     — each LLM HTTP request (openaiCompat.ts)
 *   pappy_eval                   — Pappy QC gate (pappy.ts)
 *   sqlite_save                  — SQLite saveRun (sqliteStore.ts)
 *   ahp_packet_create            — AHP root/child packet creation (ahp/helpers.ts)
 *   ahp_validation               — Pappy AHP packet evaluation
 *   trace_write                  — run-analysis JSON+MD write
 */

import { appendFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { performance } from "node:perf_hooks";

export interface ProfileEvent {
  phase: string;
  _ts: number;
  [key: string]: unknown;
}

let _outFile: string | null = null;
let _t0 = 0;

/**
 * Generate a timestamped output path for a new profiling run.
 */
export function makeProfilePath(baseDir = "./profile-runs"): string {
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  return join(baseDir, `run-${ts}.jsonl`);
}

/**
 * Initialize the profiler for a new run.
 * Must be called before any profileEmit calls.
 * Installs a global hook (__orcaProfileEmit) so instrumented packages
 * can emit events without importing this module.
 */
export function initProfiler(outputPath: string): void {
  _outFile = outputPath;
  _t0 = performance.now();
  try {
    mkdirSync(dirname(outputPath), { recursive: true });
  } catch {
    // directory likely already exists
  }
  (globalThis as Record<string, unknown>)["__orcaProfileEmit"] = profileEmit;
}

/**
 * Emit a profile event as a JSONL line.
 * _ts is milliseconds elapsed since initProfiler() was called.
 */
export function profileEmit(event: Omit<ProfileEvent, "_ts">): void {
  if (!_outFile) return;
  appendFileSync(
    _outFile,
    JSON.stringify({ ...event, _ts: performance.now() - _t0 }) + "\n",
  );
}
